<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<div class="medicine_div"><div class="form-group"><label class="col-sm-2 control-label" for="medicine_name">Medicine<span class="require-field"style="color: red;">*</span></label><div class="col-sm-3 margin_bottom_5px"><input id="medicine_name" class="form-control  text-input  medicine_name" maxlength="50" type="text" placeholder="Medicine Name"  name="medicine_name[]"></div><div class="col-sm-6"><textarea rows="1"  name="description[]"  class="form-control " id="description" maxlength="150" placeholder="Description"></textarea></div></div><div class="form-group"><div class="col-sm-offset-2 col-sm-3 margin_bottom_5px"><input class="form-control" type="text" maxlength="20" placeholder="Batch Number" name="batch_number[]"></div><div class="col-sm-2 margin_bottom_5px"><input  class="form-control text-input" min="0" type="number" onKeyPress="if(this.value.length==6) return false;"  placeholder="Quantity" name="med_quantity[]"></div><div class="col-sm-2 margin_bottom_5px"><input id="med_price" class="form-control text-input" min="1" type="number" step="0.01" onKeyPress="if(this.value.length==8) return false;"  placeholder="Price (&#36;)"  name="med_price[]"></div><div class="col-sm-2 margin_bottom_5px"><input id="" class="form-control text-input med_uniqueid" maxlength="10" type="text" placeholder="Medicine ID"	value="" name="med_uniqueid[]"></div></div><div class="form-group"><div class="col-sm-offset-2 col-sm-3 margin_bottom_5px"><textarea rows="1"  name="note[]"  class="form-control"  maxlength="150" placeholder="Note"></textarea></div><div class="col-sm-2 margin_bottom_5px"><input id="med_discount" class="form-control text-input" type="number" onKeyPress="if(this.value.length==10) return false;" step="0.01"  placeholder="Discount" name="med_discount[]"></div><div class="col-sm-2 margin_bottom_5px"><select class="form-control" name="med_discount_in[]"><option value="flat">Flat</option><option value="percentage">Percentage</option></select></div><div class="col-sm-2"></div></div><div class="form-group"><div class="col-sm-offset-2 col-sm-3 margin_bottom_5px"><input id="mfg_cmp_name" class="form-control" type="text" maxlength="50" placeholder="Manufacturer Company Name" name="mfg_cmp_name[]"></div><div class="col-sm-2 margin_bottom_5px"><div class="input-group date" data-date-format="dd/mm/yyyy"><input  type="text" name="manufactured_date[]"  class="form-control" placeholder="dd/mm/yyyy"><div class="input-group-addon" ><span class="glyphicon glyphicon-th"></span></div></div></div><div class="col-sm-2 margin_bottom_5px"><div class="input-group date" data-date-format="dd/mm/yyyy"><input  type="text" name="expiry_date[]"  class="form-control" placeholder="dd/mm/yyyy"><div class="input-group-addon" ><span class="glyphicon glyphicon-th"></span></div></div></div><div class="col-sm-offset-2 col-sm-1"><button type="button" class="btn btn-default delete_medicine_div"><i class="entypo-trash">Delete</i></button></div></div></div>
</body>
</html>